# Homework week 01

by Rahma Hayuning Astuti

## Q1. Pandas version

Answer: 2.2.2

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

## Q2. Records count

In [6]:
#get the data
import urllib.request
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
filename = 'laptops.csv'
urllib.request.urlretrieve(url, filename)

('laptops.csv', <http.client.HTTPMessage at 0x140c3f63850>)

In [8]:
#how many records are in the dataset?
data = pd.read_csv('laptops.csv')
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [10]:
# answer
data.shape

(2160, 12)

### Q3. Laptop brands

answer: 27

In [16]:
# get unique value for laptops brand
data.Brand.nunique()

27

### Q4. Missing values

answer = 3 columns

In [18]:
data.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Q5. Maximum final price

In [22]:
#max price of dell

dell_max_price = data.groupby('Brand')['Final Price'].max()
print(dell_max_price)

Brand
Acer                3691.00
Alurin               869.00
Apple               3849.00
Asus                5758.14
Deep Gaming         1639.01
Dell                3936.00
Denver               329.95
Dynabook Toshiba    1805.01
Gigabyte            3799.00
HP                  5368.77
Innjoo               431.38
Jetwing              469.27
LG                  2399.00
Lenovo              5018.14
MSI                 7150.47
Medion              3799.00
Microsoft           3747.91
Millenium           2312.71
PcCom               1949.90
Primux               599.41
Prixton              329.95
Razer               4999.01
Realme               999.00
Samsung             3699.01
Thomson              436.56
Toshiba              799.00
Vant                1217.01
Name: Final Price, dtype: float64


Answer = dell price: 3936.00

### Q6. Median value of Screen 

In [23]:
# find the median

median_before = data['Screen'].median()
print("median before: ", median_before)

median before:  15.6


In [24]:
# calculate the most frequent value in the screen

most_frequent = data['Screen'].mode()[0]
print("most frequent value: ", most_frequent)

most frequent value:  15.6


In [25]:
#fill missing value

data['Screen'].fillna(most_frequent, inplace=True)
print(data)

#calculate the median value
median_after = data['Screen'].median()
print('Median after: ', median_after)

#check if median changed

if median_before == median_after:
    print('no')
else:
    print('yes')

                                                 Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RA

C:\Users\asus\AppData\Local\Temp/ipykernel_13736/1800379108.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Screen'].fillna(most_frequent, inplace=True)


### Q7. Sum of weights

In [37]:
# Select only the "Innjoo" laptops
innjoo_laptops = data[data['Brand'] == 'Innjoo']

# Select only columns RAM, Storage, Screen
X = innjoo_laptops[['RAM', 'Storage', 'Screen']].values

In [38]:
# X^T * X
XTX = X.T @ X
print("X^T * X:\n", XTX)

X^T * X:
 [[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [32]:
import numpy as np

In [39]:
#the inverse of X^T * X
XTX_inv = np.linalg.inv(XTX)
print("Inverse of X^T * X:\n", XTX_inv)


Inverse of X^T * X:
 [[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [42]:
# Create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])
print("Array y:", y)


Array y: [1100 1300  800  900 1000 1100]


In [43]:
# w = (X^T * X)^(-1) * X^T * y
w = XTX_inv @ X.T @ y
print("Resulting w:\n", w)


Resulting w:
 [45.58076606  0.42783519 45.29127938]


In [44]:
# sum of all elements in w
w_sum = np.sum(w)
print("Sum of all elements in w:", w_sum)

Sum of all elements in w: 91.2998806299555
